-- 0029: Re-encrypt the 5 settings inserted by migration 0027 as plaintext.
--
-- Context: migration 0027 wrote plaintext payloads ('100', '60', '999', '499',
-- 'love@realreal.cc') into the `value_enc` column. The reader `getSetting()`
-- in apps/api/src/lib/settings.ts AES-256-GCM-decrypts that column. Plaintext
-- input caused decryption to throw, so `getSetting()` returned null and
-- `computeShipping()` fell back to its '100' / '0' defaults — meaning free
-- shipping never fired and the admin-side fees couldn't be edited.
--
-- This migration replaces those 5 rows' `value_enc` with properly AES-256-GCM
-- encrypted ciphertexts of the same plaintext payloads. The ciphertext was
-- generated by a one-shot Node script using the production
-- SETTINGS_ENCRYPTION_KEY (from Railway env). Re-running this migration on a
-- fresh DB will load these exact bytes — they decrypt cleanly with that key.
--
-- If you rotate SETTINGS_ENCRYPTION_KEY, you MUST re-generate this migration
-- (or run an admin re-save) before traffic hits it.

UPDATE app_settings SET value_enc='dRztNKaAcaM4Ym5x/gQNZQMoB51CF1NKFxo6zvGeMw==', updated_at=NOW(), updated_by='migration:0029' WHERE key='shipping.fee_home_delivery';
UPDATE app_settings SET value_enc='avlacOnSjzgldLhDymXMfJjRcI5tX8vvwMnBJ0VY', updated_at=NOW(), updated_by='migration:0029' WHERE key='shipping.fee_cvs';
UPDATE app_settings SET value_enc='DEjoOpa8rZDTfn4W3Itr9kzcuPuKrF+Iz/XdMfCAlQ==', updated_at=NOW(), updated_by='migration:0029' WHERE key='shipping.free_threshold_home';
UPDATE app_settings SET value_enc='AV6mFbS26l3ALNewJbtsN+oq5IzkZnVvpd6S1NzIKg==', updated_at=NOW(), updated_by='migration:0029' WHERE key='shipping.free_threshold_cvs';
UPDATE app_settings SET value_enc='VhptIHsBH58vixtom1n52N98CsoowcjukzWxkU1Hy3xpQISvXh97FOmCkzU=', updated_at=NOW(), updated_by='migration:0029' WHERE key='contact.email';
